// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Xj-b8q2VPtammqc_YMF-SYDC2MEu1YM',
    appId: '1:1086444158358:web:ba04d77264de5d2ce8b1b7',
    messagingSenderId: '1086444158358',
    projectId: 'timeless-echo-9dfa9',
    authDomain: 'timeless-echo-9dfa9.firebaseapp.com',
    storageBucket: 'timeless-echo-9dfa9.firebasestorage.app',
    measurementId: 'G-50JGW03WHZ',
    databaseURL:
        'https://timeless-echo-9dfa9-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvnITuhCq3jbmo8XXqEh0n9se4j1ZUhzw',
    appId: '1:1086444158358:android:7daa118f2705b3bee8b1b7',
    messagingSenderId: '1086444158358',
    projectId: 'timeless-echo-9dfa9',
    storageBucket: 'timeless-echo-9dfa9.firebasestorage.app',
    databaseURL:
        'https://timeless-echo-9dfa9-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEOc_j_Ue-TeZ16mMFNG9ece3vhMS46rk',
    appId: '1:1086444158358:ios:aa6f50fd47feb6c4e8b1b7',
    messagingSenderId: '1086444158358',
    projectId: 'timeless-echo-9dfa9',
    storageBucket: 'timeless-echo-9dfa9.firebasestorage.app',
    iosBundleId: 'com.example.timelessEcho',
    databaseURL:
        'https://timeless-echo-9dfa9-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Xj-b8q2VPtammqc_YMF-SYDC2MEu1YM',
    appId: '1:1086444158358:web:9ffabfb88ef77008e8b1b7',
    messagingSenderId: '1086444158358',
    projectId: 'timeless-echo-9dfa9',
    authDomain: 'timeless-echo-9dfa9.firebaseapp.com',
    storageBucket: 'timeless-echo-9dfa9.firebasestorage.app',
    measurementId: 'G-T84CPGZLNN',
  );
}
